### ISSUE TITLE
Add Laravel Support Too

### ISSUE THREAD

**Issue by Xinecraft** [abienvenu/Kyjoukan#1]
Sir,
    I found your package very interesting. It would be good if u can add laravel support for this package too,

**Comment by abienvenu** [comment]
I will have a look into it.
Meanwhile, if you don't want to install Symfony, you can use a hosted version of this software : http://kyjoukan.kyela.net/

**Comment by abienvenu** [comment]
I had a look, and found it would be quiet a lot of hassle to support both Symfony and Laravel. I will stick to Symfony. For easy deployment, I will provide a Docker image.
Of course, if somebody wants to add Laravel support in some way, feel free to contact me.

**Comment by abienvenu** [comment]
The Docker image is available, and makes deployment really easy : https://hub.docker.com/r/abienvenu/kyjoukan/
